### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [lucadentella/ItalyMap#1]
Hello!

I found link to this project from https://hackaday.com/2021/01/14/dynamic-map-of-italy-on-a-pcb/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and board schematic files in any purpose?
It would be great to see any popular open source license.

**Comment by lucadentella** [comment]
Hi Alexey! 

thanks for reminding me of this: this are educational projects so I often forget to explicitly indicate the license.
I normally go for **CC BY 4.0**

**Comment by vazhnov** [comment]
Great! Thank you!
